### ISSUE TITLE
Good Works. 

### ISSUE THREAD

**Issue by BlueBlueFF** [FreedomIntelligence/ALLaVA#1]
Why Vit encoder is frozen? It is different with LLava

**Comment by liyang-7** [comment]
Original llava-1.5 vit is frozen during two-stage training

**Comment by g-h-chen** [comment]
> Original llava-1.5 vit is frozen during two-stage training

Exactly. In case you are interested, in Table 6 of [ShareGPT4V paper](https://arxiv.org/pdf/2311.12793.pdf), they provide a simple ablation study on the trainability of ViT.
