### ISSUE TITLE
MME Score

### ISSUE THREAD

**Issue by qingyuanxingsi** [FreedomIntelligence/ALLaVA#10]
Thanks for your great work! If seems that the MME score is Perception+ reasoning?

**Comment by g-h-chen** [comment]
Thanks for your interest for our work. The presented MME score is Perception + Cognition.

**Comment by Isaachhh** [comment]
I think you should clarify that on your paper, GitHub and HuggingFace.

For example, you can find LLaVA-v1.5-13B achieves 295.36 on MME-C [here](https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/tree/Evaluation?tab=readme-ov-file), but you treat it as **0** in your paper.

And it is an unfair comparison for those models  only reporting MME perception score.

**Comment by g-h-chen** [comment]
Thanks for pointing out the mistake!

We took the MME result of LLaVA-v1.5-13B from Table 2 of their original [paper](https://arxiv.org/pdf/2310.03744.pdf). There seems to be a similar problem for LLaVA-v1.5-7B in Table 1 of the [LLaVA-Phi paper](https://arxiv.org/pdf/2401.02330.pdf). **We did not deliberately manipulate the result.** We will update our paper soon.

Best,
Guiming
