### ISSUE TITLE
 Laion image

### ISSUE THREAD

**Issue by Cuiunbo** [FreedomIntelligence/ALLaVA#12]
Hi, great work!
I have downloaded the Laion image pack available on Hugging Face and noticed that there's a mismatch between the images and the QAs in the ALLaVA-LAION . Could you please check if this is indeed the case?
Thank you.

Here is a case.
http://slideplayer.com/slide/3861701/13/images/90/Statistical+versus+clinical+significance.jpg

The image depicts a vibrant and bustling cityscape at night. Tall skyscrapers adorned with colorful lights rise against the dark sky, creating a dazzling display of urban architecture. The streets below are illuminated by the glow of streetlights and the headlights of moving vehicles. A river runs through the city, reflecting the shimmering lights of the buildings. The skyline is dominated by a mix of modern and traditional structures, showcasing a dynamic blend of architectural styles.

**Comment by g-h-chen** [comment]
Hi @Cuiunbo ,

Sorry for the late reply. We have updated the annotation files of [captions](https://huggingface.co/datasets/FreedomIntelligence/ALLaVA-4V/blob/main/allava_laion/ALLaVA-Caption-LAION-4V.json) and [instructions](https://huggingface.co/datasets/FreedomIntelligence/ALLaVA-4V/blob/main/allava_laion/ALLaVA-Instruct-LAION-4V.json) on LAION. Basically we delete the samples with image-text inconsistency, yielding 489044 clean samples in each file (originally 505588). However, there might still be some mismatched samples. Please tell us the sample id if you find any!

Best,
Guiming

**Comment by Cuiunbo** [comment]
Wonderful! I have already used some methods to filter the dataset, and the filtering ratio is also at 2%, same as yours.
