### ISSUE TITLE
Inquiry about GPT-4 API Usage

### ISSUE THREAD

**Issue by JCruan519** [FreedomIntelligence/ALLaVA#13]
Hello,

I find this work significant and have a question regarding the process: Are images encoded in base64 and input alongside text prompts into GPT-4v? Additionally, if feasible, could you provide the code snippet used for calling the GPT-4 API that includes this functionality?

Thank you for your assistance.

**Comment by Shunian-Chen** [comment]
Thank you for your interest in our work! We followed the official OpenAI API tutorial, and the specific call method is as follows.
```python
def get_image(image_path):

    img = Image.open(image_path).convert('RGB')
    img_type = img.format
    
    byte_arr = io.BytesIO()
    img.save(byte_arr, format=img_type)
    byte_arr.seek(0)

    return byte_arr, img_type

def request_api(sample, api_key, model = "gpt-4-vision-preview", timeout = TIME_OUT, temperature = 0.5):

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}"
    }

    # process images
    images = []
    img_types = []
    for img in sample['img_list']:
        image, img_type = get_image(img)
        image = base64.b64encode(image.getvalue()).decode()
        images.append(image)
        img_types.append(img_type)

    # prepare content
    content = []
    content.append({"type": "text", "text": sample['context']})
    for image, img_type in zip(images, img_types):
        content.append(
            {
                "type": "image_url",
                "image_url": {
                    "url": f"data:image/{img_type};base64,{image}"
                }
            }
        )

    payload = {
        "model": model,
        "messages": [
        {
            "role": "user",
            "content": content
        }
        ],
        "max_tokens": 256,
        "temperature": temperature,
    }
    
    # request
    response = requests.post("https://api.openai.com/v1/chat/completions", headers=headers, json=payload, verify=False, timeout=timeout)

    return response
```
I hope you find this helpful. Should you have any further questions, please feel free to ask.

**Comment by conan1024hao** [comment]
@Shunian-Chen Hi, thanks for the excellent code! How did you scale it to handle 1M data? I tried running this code on my dataset but it take about 1s per image even with async applied. Processing 1M data would take around 11 days then...

**Comment by Shunian-Chen** [comment]
> @Shunian-Chen Hi, thanks for the excellent code! How did you scale it to handle 1M data? I tried running this code on my dataset but it take about 1s per image even with async applied. Processing 1M data would take around 11 days then...

When processing large amounts of data, consider using multi-threading for acceleration and utilizing multiple OpenAI accounts to increase TPM or RPM limits. Note that the actual running speed ultimately depends on the machine's performance, internet speed, and OpenAI API rate limits.
