### ISSUE TITLE
laion数据集部分url失效

### ISSUE THREAD

**Issue by liyang-7** [FreedomIntelligence/ALLaVA#2]
你好 请问能公开下数据集中laion部分的图片吗
目前laion部分公开的是url，大概有10%的链接是失效的，如果之前没有下载过laion数据集，那么这部分的数据就没法在训练中使用，请问是否能公开下laion部分的图片

**Comment by chizhanyuefeng** [comment]
同求数据

**Comment by g-h-chen** [comment]
Thanks for your interest on our work! We are checking the properness of re-publishing these images. Currently, please manually download the images following instructions [here](https://github.com/FreedomIntelligence/ALLaVA?tab=readme-ov-file#laion). Stay tuned!

**Comment by g-h-chen** [comment]
We have updated the laion images as well as the download scripts.
