### ISSUE TITLE
So bad

### ISSUE THREAD

**Issue by lucasjinreal** [FreedomIntelligence/ALLaVA#4]
![image](https://github.com/FreedomIntelligence/ALLaVA/assets/21303438/15f668c2-57df-49cf-b786-f1a04e6e02ad)

**Comment by g-h-chen** [comment]
Hi @lucasjinreal ,

Thanks for using our demo.

1. Our model does not well support Chinese. This is because ALLaVA is based on Phi which is an English model, and our training data are mainly in English as well.
2. We only support one image input per session. 

Best,
Guiming

**Comment by lucasjinreal** [comment]
Any consideration to enhance Chinese?

**Comment by wabyking** [comment]
Sure, we are working on it. Once getting it done, we will let you know.
