### ISSUE TITLE
no laion images

### ISSUE THREAD

**Issue by phellonchen** [FreedomIntelligence/ALLaVA#5]
There are no images for laion in https://huggingface.co/datasets/FreedomIntelligence/ALLaVA-4V/resolve/main/allava_laion/images.zip?download=true

**Comment by g-h-chen** [comment]
Hi @phellonchen , thanks for your close attention on our repo! We are encountering network issue when uploading the images. We've split them into chunks and they are still being uploaded, which is expected to finish **in 15 hours**. **The download scripts will be updated as well.** Stay tuned!

**Comment by phellonchen** [comment]
There are only 181393 images in https://huggingface.co/datasets/Vision-Flan/vision-flan_191-task_1k/resolve/main/image_191-task_1k.zip while the number is 203,065 in the Table in Readme.

Maybe the additional 30K images are missing.

**Comment by g-h-chen** [comment]
The number of images you report for both datasets is correct. An image can correspond to more than 1 sample.

**Comment by g-h-chen** [comment]
We have updated the laion images as well as the download scripts.

**Comment by phellonchen** [comment]
Some images are missing.
