### ISSUE TITLE
Train

### ISSUE THREAD

**Issue by TerryYiDa** [FreedomIntelligence/ALLaVA#9]
能不能readme.md更新一下详细的训练指导过程？谢谢。

**Comment by g-h-chen** [comment]
Hi @TerryYiDa ,

I think there is a detailed instruction and a complete code base [here](https://github.com/haotian-liu/LLaVA?tab=readme-ov-file#train), based on which we trained our ALLaVA. Our dataset [ALLaVA-4V](https://huggingface.co/datasets/FreedomIntelligence/ALLaVA-4V) has been converted to the format that can be used for training on the fly. 

Best,
Guiming
